<?php
declare(strict_types=1);

$source=(string)file_get_contents(__DIR__.'/main.php');
$bad="foreach(['skills'=>'مهارات','interests'=>'اهتمامات','study_work'=>'دراسة/عمل','offers'=>'أقدم','seeks'=>'أبحث'] as \$k=>\$lab)if(!empty(\$u[\$k])):?><span class=\"chip\"><?=\$lab?>: <?=h((string)\$u[\$k])?></span><?php endforeach;?>";
$good="foreach(['skills'=>'مهارات','interests'=>'اهتمامات','study_work'=>'دراسة/عمل','offers'=>'أقدم','seeks'=>'أبحث'] as \$k=>\$lab):if(!empty(\$u[\$k])):?><span class=\"chip\"><?=\$lab?>: <?=h((string)\$u[\$k])?></span><?php endif;endforeach;?>";
$source=str_replace($bad,$good,$source,$count);if($count!==1){http_response_code(500);echo 'OYYA compile guard failed.';exit;}
$source=str_replace('$usersCount=count($users);','$usersCount=count(oyya_test_users());',$source);$source=str_replace('__DIR__',var_export(__DIR__,true),$source);$tmp=sys_get_temp_dir().'/oyya-main-'.sha1($source).'.php';file_put_contents($tmp,$source,LOCK_EX);ob_start();require $tmp;$out=(string)ob_get_clean();
$isMap=((string)($_GET['view']??'feed'))==='map';$mapAssets='<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maplibre-gl@5.7.0/dist/maplibre-gl.css"><link rel="stylesheet" href="/oyya-map-snap.css?v=1"><script defer src="https://cdn.jsdelivr.net/npm/maplibre-gl@5.7.0/dist/maplibre-gl.js"></script><script defer src="/oyya-vector-map.js?v=7"></script>';$experienceAsset=$isMap?'':'<script defer src="/oyya-experience.js?v=4"></script>';$mobileMeta='<meta name="theme-color" content="#fffc00"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="OYYA"><link rel="apple-touch-icon" href="/oyya-icon-192.svg">';
$assets=$mobileMeta.$mapAssets.'<link rel="stylesheet" href="/oyya-experience.css?v=2"><link rel="stylesheet" href="/oyya-modern-colors.css?v=2"><link rel="stylesheet" href="/oyya-themes.css?v=2"><link rel="stylesheet" href="/oyya-profiles.css?v=1"><link rel="stylesheet" href="/oyya-social.css?v=1"><link rel="stylesheet" href="/oyya-production.css?v=1"><link rel="stylesheet" href="/oyya-finish.css?v=2">'.$experienceAsset.'<script defer src="/oyya-route-guard.js?v=1"></script><script defer src="/oyya-nav-gesture.js?v=5"></script><script defer src="/oyya-composer.js?v=3"></script><script defer src="/oyya-themes.js?v=1"></script><script defer src="/oyya-profiles.js?v=1"></script><script defer src="/oyya-social.js?v=2"></script><script defer src="/oyya-production.js?v=1"></script><script defer src="/oyya-finish.js?v=3"></script><script defer src="/oyya-reels.js?v=1"></script><script defer src="/oyya-install-ui.js?v=2"></script><script defer src="/oyya-media-guard.js?v=1"></script>';
if(stripos($out,'</head>')!==false)$out=str_ireplace('</head>',$assets.'</head>',$out);echo $out;
