<?php
declare(strict_types=1);

function oyya_extra_boot(): void {foreach(['entity_gallery','verification_requests','views'] as $f)if(!file_exists(oyya_path($f)))oyya_write($f,[]);}oyya_extra_boot();

function oyya_create_media_post(string $uid,array $in,?array $file=null): array {
    $text=trim((string)($in['text']??''));$mediaId='';
    if($file&&(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_OK)){[$ok,$res]=oyya_upload_media($uid,$file,'post');if(!$ok)return[false,$res];$mediaId=$res;}
    if($text===''&&$mediaId==='')return[false,'اكتب شيئًا أو أضف وسائط.'];
    $p=oyya_read('posts');$p[]=['id'=>oyya_id(),'user_id'=>$uid,'text'=>$text,'media_id'=>$mediaId,'nearby'=>!empty($in['nearby']),'kind'=>'post','created_at'=>oyya_now()];oyya_write('posts',$p);return[true,'تم النشر.'];
}
function oyya_add_audio_comment(string $uid,string $post,array $file): array {[$ok,$res]=oyya_upload_media($uid,$file,'voice_comment');if(!$ok)return[false,$res];$c=oyya_read('comments');$c[]=['id'=>oyya_id(),'post_id'=>$post,'user_id'=>$uid,'text'=>'','media_id'=>$res,'created_at'=>oyya_now()];oyya_write('comments',$c);foreach(oyya_read('posts') as $p)if(($p['id']??'')===$post&&($p['user_id']??'')!==$uid)oyya_notify((string)$p['user_id'],'لديك تعليق صوتي جديد.','comment');return[true,'تم إرسال التعليق الصوتي.'];}
function oyya_entity_gallery_add(string $uid,string $entityId,array $file,string $caption=''): array {$owned=false;foreach(oyya_read('entities') as $e)if(($e['id']??'')===$entityId&&($e['owner_id']??'')===$uid)$owned=true;if(!$owned)return[false,'لا تملك هذه الصفحة.'];[$ok,$res]=oyya_upload_media($uid,$file,'gallery');if(!$ok)return[false,$res];$r=oyya_read('entity_gallery');$r[]=['id'=>oyya_id(),'entity_id'=>$entityId,'media_id'=>$res,'caption'=>trim($caption),'created_at'=>oyya_now()];oyya_write('entity_gallery',$r);return[true,'تمت إضافة العنصر للمعرض.'];}
function oyya_request_verification(string $uid): array {$r=oyya_read('verification_requests');foreach($r as $x)if(($x['user_id']??'')===$uid&&($x['status']??'')==='pending')return[false,'طلبك قيد المراجعة.'];$r[]=['id'=>oyya_id(),'user_id'=>$uid,'status'=>'pending','created_at'=>oyya_now()];oyya_write('verification_requests',$r);return[true,'تم إرسال طلب التحقق التجريبي.'];}
function oyya_creator_scores(): array {$scores=[];foreach(oyya_users() as $u)$scores[$u['id']]=0;foreach(oyya_read('posts') as $p)$scores[$p['user_id']]=($scores[$p['user_id']]??0)+2;foreach(oyya_read('likes') as $l){foreach(oyya_read('posts') as $p)if(($p['id']??'')===($l['post_id']??''))$scores[$p['user_id']]=($scores[$p['user_id']]??0)+1;}arsort($scores);return$scores;}
function oyya_search_world(string $q): array {$q=mb_strtolower(trim($q));if($q==='')return['users'=>[],'entities'=>[],'posts'=>[]];$has=fn($s)=>mb_strpos(mb_strtolower((string)$s),$q)!==false;$users=array_values(array_filter(oyya_users(),fn($u)=>$has(($u['name']??'').' '.($u['city']??'').' '.($u['skills']??'').' '.($u['interests']??'').' '.($u['study_work']??''))));$entities=array_values(array_filter(oyya_read('entities'),fn($e)=>$has(($e['name']??'').' '.($e['description']??'').' '.($e['city']??''))));$posts=array_values(array_filter(oyya_read('posts'),fn($p)=>$has($p['text']??'')));return compact('users','entities','posts');}
function oyya_memories(string $uid): array {$mine=array_values(array_filter(oyya_read('posts'),fn($p)=>($p['user_id']??'')===$uid));usort($mine,fn($a,$b)=>strcmp((string)($a['created_at']??''),(string)($b['created_at']??'')));return array_slice($mine,0,10);}
function oyya_media_html(?array $m): string {if(!$m)return'';$url=htmlspecialchars((string)$m['url'],ENT_QUOTES,'UTF-8');$mime=(string)$m['mime'];if(str_starts_with($mime,'image/'))return'<img class="postMedia" src="'.$url.'" alt="وسائط المنشور" loading="lazy">';if(str_starts_with($mime,'video/'))return'<video class="postMedia" src="'.$url.'" controls playsinline preload="metadata"></video>';if(str_starts_with($mime,'audio/'))return'<audio src="'.$url.'" controls preload="metadata"></audio>';return'';}
